-- English Space — Zhenya
-- Запускайте файл целиком в Supabase SQL Editor.
-- Скрипт не удаляет существующие данные.

create extension if not exists pgcrypto;

create table if not exists public.homework_progress (
  id bigint generated by default as identity primary key,
  submission_id uuid not null unique default gen_random_uuid(),
  student_id text not null,
  lesson_id text not null,
  status text not null default 'draft',
  answers jsonb not null default '{}'::jsonb,
  score_correct integer,
  score_total integer,
  score_percent integer,
  checked_at timestamptz,
  submitted_at timestamptz,
  locked_at timestamptz,
  report_status text not null default 'not_sent',
  report_sent_at timestamptz,
  report_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint homework_progress_student_lesson_key unique (student_id, lesson_id),
  constraint homework_progress_status_check check (status in ('draft','submitted_pending_report','submitted')),
  constraint homework_progress_report_status_check check (report_status in ('not_sent','pending','sent','failed')),
  constraint homework_progress_answers_object_check check (jsonb_typeof(answers) = 'object'),
  constraint homework_progress_scores_check check (
    (score_correct is null or score_correct >= 0)
    and (score_total is null or score_total >= 0)
    and (score_correct is null or score_total is null or score_correct <= score_total)
    and (score_percent is null or score_percent between 0 and 100)
  ),
  constraint homework_progress_submission_dates_check check (
    status = 'draft' or (submitted_at is not null and locked_at is not null)
  ),
  constraint homework_progress_submitted_report_check check (
    status <> 'submitted' or report_status = 'sent'
  ),
  constraint homework_progress_report_sent_at_check check (
    report_status <> 'sent' or report_sent_at is not null
  )
);

create table if not exists public.vocabulary_progress (
  id bigint generated by default as identity primary key,
  student_id text not null,
  word_key text not null,
  status text not null default 'new',
  learned_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vocabulary_progress_student_word_key unique (student_id, word_key),
  constraint vocabulary_progress_status_check check (status in ('new','known','difficult')),
  constraint vocabulary_progress_learned_at_check check (status <> 'known' or learned_at is not null)
);

create table if not exists public.vocabulary_topic_progress (
  id bigint generated by default as identity primary key,
  student_id text not null,
  topic_id text not null,
  tests jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vocabulary_topic_progress_student_topic_key unique (student_id, topic_id),
  constraint vocabulary_topic_progress_tests_array_check check (jsonb_typeof(tests) = 'array')
);

create table if not exists public.grammar_progress (
  id bigint generated by default as identity primary key,
  student_id text not null,
  topic_id text not null,
  passed boolean not null default false,
  attempts integer not null default 0,
  best_score integer not null default 0,
  passed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint grammar_progress_student_topic_key unique (student_id, topic_id),
  constraint grammar_progress_attempts_check check (attempts >= 0),
  constraint grammar_progress_best_score_check check (best_score between 0 and 100),
  constraint grammar_progress_passed_at_check check (passed = false or passed_at is not null)
);

create table if not exists public.telegram_recipients (
  id uuid primary key default gen_random_uuid(),
  student_id text not null unique,
  chat_id bigint not null unique,
  message_thread_id bigint,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.material_publications (
  id uuid primary key default gen_random_uuid(),
  student_id text not null,
  material_type text not null,
  material_id text not null,
  notification_version integer not null default 1,
  status text not null default 'pending',
  payload jsonb not null default '{}'::jsonb,
  telegram_message_id bigint,
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint material_publications_unique_notification unique (student_id, material_type, material_id, notification_version),
  constraint material_publications_status_check check (status in ('pending','sent','failed','skipped')),
  constraint material_publications_payload_object_check check (jsonb_typeof(payload) = 'object'),
  constraint material_publications_version_check check (notification_version >= 1)
);

create or replace function public.set_progress_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.prevent_homework_resubmission()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  request_role text := coalesce(current_setting('request.jwt.claim.role', true), '');
  request_claims text := coalesce(current_setting('request.jwt.claims', true), '');
  privileged boolean;
begin
  if request_role = '' and request_claims <> '' then
    begin
      request_role := coalesce((request_claims::jsonb ->> 'role'), '');
    exception when others then
      request_role := '';
    end;
  end if;
  privileged := current_user in ('postgres','service_role') or request_role = 'service_role';
  if old.status not in ('submitted_pending_report','submitted') then
    return new;
  end if;

  if new.student_id is distinct from old.student_id
    or new.lesson_id is distinct from old.lesson_id
    or new.answers is distinct from old.answers
    or new.score_correct is distinct from old.score_correct
    or new.score_total is distinct from old.score_total
    or new.score_percent is distinct from old.score_percent
    or new.checked_at is distinct from old.checked_at
    or new.submitted_at is distinct from old.submitted_at
    or new.locked_at is distinct from old.locked_at
    or new.submission_id is distinct from old.submission_id then
      raise exception 'Submitted homework is locked and cannot be changed';
  end if;

  if old.status = 'submitted' then
    if new.status is distinct from old.status
      or new.report_status is distinct from old.report_status
      or new.report_sent_at is distinct from old.report_sent_at
      or new.report_error is distinct from old.report_error then
        raise exception 'Submitted homework is immutable';
    end if;
    return new;
  end if;

  -- Для submitted_pending_report безопасное повторное сохранение тех же значений допустимо.
  if new.status = old.status
    and new.report_status = old.report_status
    and new.report_sent_at is not distinct from old.report_sent_at
    and new.report_error is not distinct from old.report_error then
      return new;
  end if;

  if not privileged then
    raise exception 'Only the server function can update report delivery fields';
  end if;

  if new.status not in ('submitted_pending_report','submitted') then
    raise exception 'Invalid homework status transition';
  end if;

  if new.status = 'submitted' and (new.report_status <> 'sent' or new.report_sent_at is null) then
    raise exception 'Submitted status requires a sent report';
  end if;

  return new;
end;
$$;

-- Триггеры создаются повторно безопасно.
drop trigger if exists a_prevent_homework_resubmission on public.homework_progress;
create trigger a_prevent_homework_resubmission
before update on public.homework_progress
for each row execute function public.prevent_homework_resubmission();

DO $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'homework_progress',
    'vocabulary_progress',
    'vocabulary_topic_progress',
    'grammar_progress',
    'telegram_recipients',
    'material_publications'
  ] loop
    execute format('drop trigger if exists z_set_updated_at on public.%I', table_name);
    execute format('create trigger z_set_updated_at before update on public.%I for each row execute function public.set_progress_updated_at()', table_name);
  end loop;
end;
$$;

alter table public.homework_progress enable row level security;
alter table public.vocabulary_progress enable row level security;
alter table public.vocabulary_topic_progress enable row level security;
alter table public.grammar_progress enable row level security;
alter table public.telegram_recipients enable row level security;
alter table public.material_publications enable row level security;

-- Политики персонального сайта Жени.
drop policy if exists zhenya_homework_select on public.homework_progress;
drop policy if exists zhenya_homework_insert on public.homework_progress;
drop policy if exists zhenya_homework_update on public.homework_progress;
create policy zhenya_homework_select on public.homework_progress for select to anon using (student_id = 'zhenya');
create policy zhenya_homework_insert on public.homework_progress for insert to anon with check (student_id = 'zhenya');
create policy zhenya_homework_update on public.homework_progress for update to anon using (student_id = 'zhenya') with check (student_id = 'zhenya');

DO $$
declare
  table_name text;
  policy_prefix text;
begin
  foreach table_name in array array['vocabulary_progress','vocabulary_topic_progress','grammar_progress'] loop
    policy_prefix := 'zhenya_' || table_name;
    execute format('drop policy if exists %I on public.%I', policy_prefix || '_select', table_name);
    execute format('drop policy if exists %I on public.%I', policy_prefix || '_insert', table_name);
    execute format('drop policy if exists %I on public.%I', policy_prefix || '_update', table_name);
    execute format('drop policy if exists %I on public.%I', policy_prefix || '_delete', table_name);
    execute format('create policy %I on public.%I for select to anon using (student_id = ''zhenya'')', policy_prefix || '_select', table_name);
    execute format('create policy %I on public.%I for insert to anon with check (student_id = ''zhenya'')', policy_prefix || '_insert', table_name);
    execute format('create policy %I on public.%I for update to anon using (student_id = ''zhenya'') with check (student_id = ''zhenya'')', policy_prefix || '_update', table_name);
    execute format('create policy %I on public.%I for delete to anon using (student_id = ''zhenya'')', policy_prefix || '_delete', table_name);
  end loop;
end;
$$;

revoke all on table public.homework_progress from anon, authenticated;
revoke all on table public.vocabulary_progress from anon, authenticated;
revoke all on table public.vocabulary_topic_progress from anon, authenticated;
revoke all on table public.grammar_progress from anon, authenticated;
grant select, insert, update on table public.homework_progress to anon;
grant select, insert, update, delete on table public.vocabulary_progress to anon;
grant select, insert, update, delete on table public.vocabulary_topic_progress to anon;
grant select, insert, update, delete on table public.grammar_progress to anon;
grant usage, select on all sequences in schema public to anon;

revoke all on table public.telegram_recipients from anon, authenticated;
revoke all on table public.material_publications from anon, authenticated;
grant all on table public.telegram_recipients to service_role;
grant all on table public.material_publications to service_role;
grant all on table public.homework_progress to service_role;
grant all on table public.vocabulary_progress to service_role;
grant all on table public.vocabulary_topic_progress to service_role;
grant all on table public.grammar_progress to service_role;
